version: "3.9"

services:
  web:
    build: ./web
#    commands: gunicorn core.wsgi:application --bind 0.0.0.0:9000
    command: python manage.py runserver 0.0.0.0:9000
    container_name: django_web
    volumes:
      - ./web:/app
    env_file:
      - ./web/.env
    ports:
      - "9000:9000"
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql
    env_file:
      - ./web/.env
    ports:
      - "5433:5432"

volumes:
  db-data: