version: "3.3"

services:
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - static_volume:/app/static
    ports:
      - "5000:80"
    depends_on:
      - web
  web:
    build: ./web
    command: gunicorn core.wsgi:application --bind 0.0.0.0:9000
#    command: python manage.py runserver 0.0.0.0:9000
    container_name: django_web
    volumes:
      - ./web:/app
      - static_volume:/app/static
    env_file:
      - ./web/.env
    expose:
      - 9000
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql
    env_file:
      - ./web/.env
    ports:
      - "5433:5432"

volumes:
  db-data:
  static_volume: