from .test_comment import CommentApiViewTest, CommentCreateUpdateDeleteApiView
from .test_hotel import HotelApiViewTest, HotelRUDApiViewTest
from .test_room import RoomApiViewTest, CreateDeleteUpdateApiViewTest
