# Generated by Django 4.0.3 on 2022-06-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['name'], name='idx_hotel_name'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['beds'], name='idx_room_beds'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['price'], name='idx_room_price'),
        ),
    ]
