# Generated by Django 4.0.7 on 2022-08-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_idx_hotel_name_room_idx_room_beds_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='comment_rating_gte_1_and_lte_5'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(check=models.Q(('beds__gte', 1), ('beds__lte', 4)), name='check_beds_gte_1_and_lte_4'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(check=models.Q(('beds__gte', 1), ('beds__lte', 1000)), name='check_size_gte_1_and_lte_1000'),
        ),
    ]
