# Generated by Django 4.0.7 on 2022-08-06 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('hotel', '0003_comment_comment_rating_gte_1_and_lte_5_and_more'),
    ]

    operations = [
        migrations.RunSQL("""
        CREATE OR REPLACE FUNCTION check_limit_of_hotels_per_owner()
            RETURNS TRIGGER
            LANGUAGE plpgsql AS
            $$
                DECLARE amount int;
                BEGIN
                    amount := (SELECT COUNT(*) FROM hotel_hotel WHERE owner_id = NEW.owner_id);
                    IF amount >= 4 THEN
                        RAISE EXCEPTION 'Every owner can have max 4 hotels!';
                    END IF;
                    RETURN NEW;
                END;
            $$;
        CREATE OR REPLACE TRIGGER check_create_hotel
            BEFORE INSERT ON hotel_hotel
            FOR EACH ROW
            EXECUTE PROCEDURE check_limit_of_hotels_per_owner();
        """, """
        DROP TRIGGER IF EXISTS check_create_hotel ON hotel_hotel;
        DROP FUNCTION IF EXISTS check_limit_of_hotels_per_owner;
        """)
    ]
